name: Bug report
description: Report something that's broken or not working as expected.
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What's happening / what you want
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: |
        Numbered steps, e.g.
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected
    validations:
      required: true
  - type: textarea
    id: out-of-scope
    attributes:
      label: Anything out of scope
    validations:
      required: false
